jenkins:
  systemMessage: "Jenkins - Moncada Gold CI/CD Pipeline"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin123"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: |
      pipelineJob('moncada-gold-inventory') {
        description('Pipeline CI para Moncada Gold Inventory')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/shadow4646/moncada-gold-inventory.git')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          githubPush()
        }
      }
